### ISSUE TITLE
Handle old `EMMO` Python package version tags

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMOntoPy#272]
All the version tags pointing to the old `EMMO` package should be dealt with.
As I see it, we have the following options:

1. Delete them.
2. Rename them.
   For example, prepend them all with `old-` or `EMMO-` or similar.
3. Create a new GitHub repository for EMMOntoPy, archiving this one.
   Then the tags can be deleted in the new repository, but kept here.

What do you think @francescalb and @jesper-friis?

**Comment by jesper-friis** [comment]
I am fine with option 2.
