### ISSUE TITLE
Review default colours and style in ontopy/graph.py

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMOntoPy#345]
EMMO has ![too many relations](https://github.com/emmo-repo/EMMO/blob/updated-readme-and-figures/doc/relations.png) to give all of them a unique default colour/style combination. One possibility could be to make mereological, topological and semiotical relations solid, dashed and dotted respectively. For colours we could either:

- leave it to the user to define them for each plot
- define explicit colours for some high-level/important relations within each category
- define a colour cycle and more or less randomly assign them to the relations present in the graph (pros: all relations will get a unique colour by default; cons: the same relation may get different colours in two different graphs)

It is also possible to support all three alternatives.

**Comment by francescalb** [comment]
I have now added so that if a defualt is not given for the given relation, the default style olive, solid is used. I think it would be smart to have an option where edgelabels are added only for those relations that do not hava a unique style.

**Comment by francescalb** [comment]
Closed with PR469
