### ISSUE TITLE
Drop Python 3.6 support - extend Python >3.7 support

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMOntoPy#486]
As seen [here](https://github.com/emmo-repo/EMMOntoPy/actions/runs/3197601428/jobs/5221032835), when running PyTest for EMMOntoPy in a Python 3.6 environment, it is impossible to install the dependencies as they are setup now.

Since Python 3.6 is no longer supported (support ended [9 months ago](https://endoflife.date/python)), I think it's fine to push up EMMOntoPy support to require Python 3.7 at minimum?
If this is not desired, we must put some effort into supporting all - or most - of the EMMOntoPy features in a Python 3.6 environment. At the very least making it installable.

It might also be nice to start testing EMMOntoPy functionality in newer Python versions: 3.8, 3.9, 3.10?
Especially considering Python 3.7 support is stopping [within 8 months](https://endoflife.date/python).

**Comment by CasperWA** [comment]
There's some information [here](https://packaging.python.org/en/latest/guides/dropping-older-python-versions/).
But in general I'd up the "minor" version (indeed releasing a v0.5) and state clearly in the release notes that v0.4.x will be the last series of versions to support Python 3.6 (even though it technically doesn't even do that now).

One can go a lot further and implement meta packages that proxy to the real packages depending on the python interpreter used including printing deprecation warnings etc. That's overkill here I think.

Another way is to simply include a print statement/deprecation warning that's blurted out whenever _anything_ is imported from the any of the `ontopy` or `emmopy` packages. This would by default only be shown once in a session, but be emitted _every_ time an import is performed.
I don't think this is nice either though.

I'd just state it clearly in the release notes and let that be that. `pip` will automatically only install the 0.4.x versions when using a Python 3.6 interpreter, due to the metadata we've included/will exclude in `setup.py`.

In addition, according to this metadata EMMOntoPy officially _only_ supports Python 3.6 and Python 3.7 as of now - hence my suggestion to add 3.8, 3.9, and possibly 3.10 - with the additions being done in a PR where we can test them out and ensure all desired features work as intended with the different versions, before then merging it into `master` :)

**Comment by CasperWA** [comment]
As a note, I tried to accommodate the Python 3.6 dependency versions in the requirements, so that it can at least install, but it seems the Excel parser does not work - at least `xlsx` is _not_ supported (see [this CI run](https://github.com/emmo-repo/EMMOntoPy/actions/runs/3198209433/jobs/5222445292#step:6:171)).
I think this is the strongest argument for dropping Python 3.6 support.

It is worth noting that the current tests are far from covering all the functionalities of EMMOntoPy, and hence it is possible other functionalities also do not work as intended.
Note, this is of course not exclusive to Python 3.6.

**Comment by francescalb** [comment]
I suggest completely dropping python 3.6, since in practice we have not been testing it at all, all along.

**Comment by jesper-friis** [comment]
I agree with your arguments for dropping support for 3.6 and instead including 3.8, 3.9 and 3.10.
