### ISSUE TITLE
Remove or rename "old" version tags

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMOntoPy#547]
The old version tags (when this repo was `EMMO-Python` and just called the `emmo` package once installed) are interfering a bit with the changelog generation.
I think we have accommodated these tags for long enough that I don't see a reason why we should keep them around.

As an alternative, we can prepend them with `old-` or `emmo-python-` or something like this?

**Comment by francescalb** [comment]
I think pre-pending with old could work.

**Comment by francescalb** [comment]
I agree with just deleting them. There is not reason to keep old things hanging around which do not have any value for anyone. I will proceed with removing all "1.0...." releases and tags

**Comment by francescalb** [comment]
Deleted old tags and releases that were done when the package was called EMMO-Python. No-one is using these old tags and I see no reason to pollute the internet with them.
