### ISSUE TITLE
Add client side redirection in generated html documentation

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMOntoPy#552]
It is not possible to make server-side redirection rules that would redirect http://emmo.info/DOMAIN to a turtle file with the inferred ontology for DOMAIN and http://emmo.info/DOMAIN#NAME to the human readable html documentation of the IRI
(for security reasons the fragment is stripped of before reaching the server). 

However, what we can do, is to redirect http://emmo.info/DOMAIN to the human readable html page and then add the following small javascript to the header of the generated html page, which will redirect the user further to the turtle file if the user did not specify any #NAME:

```html
  <!-- ontodoc: without fragment, redirect to <TARGET> -->
  <script>
    if (window.location.hash == "") {
      window.location.href = “<TARGET>”;
    }
  </script>
```

where `<TARGET>` is an URL to the inferred turtle file. 

To support this, add a `--redirect[=<TARGET>]` option to ontodoc, that adds a javascript redirection to the header of the generated html documentation. If the argument is omitted, it will default to the name of the generated html file with the `.html` file extension replaced with `.ttl`.

**Comment by francescalb** [comment]
This does not work for Protégé so we agreed to close this issue for now.
