### ISSUE TITLE
utils line 112 in get_iri_name link = "{lowerlabel}" vs "{label}"

### ISSUE THREAD

**Issue by francescalb** [emmo-repo/EMMOntoPy#562]
Which should be default? There seems to be disagreement. I prefer label.

More importantly, the lowerlabel does not introduce spaces or hyphens as described, but just makes lower label e.g. hasProperty -> hasproperty. Also, ontograph only returns black bold arrows for object properties (i.e. styles are not updated correctly)

This should be checked out in e.g. ontograph.

**Comment by francescalb** [comment]
ontograph --root=Reductionistic --relations=all --legend --parents=0 --format=png emmo-inferred red_relationsfirst.png

example of ontograph command to use

**Comment by francescalb** [comment]
@jesper-friis  why do you want relations to be written out as lowerlabel as default? I think hasTemporalTile is better than hastemporaltile (which is the result of asking for lowerlabel right now).

**Comment by jesper-friis** [comment]
Probably Just me not thinking. I can't recall exactly the part of the code you are referring to. We could have a quick look at the code together if you want.

**Comment by francescalb** [comment]
It is one of the arguments in asstring. Tou changed it from default 'label' to 'lowerlabel' in the previous PR. 

https://github.com/emmo-repo/EMMOntoPy/blob/7918322d3f70757c0f4b2c097c707a151879efe5/ontopy/utils.py#L110

**Comment by francescalb** [comment]
After a discussion it was agreed that label should be kept as default
