### ISSUE TITLE
Auto-merge dependabot PRs workflow invalid

### ISSUE THREAD

**Issue by CasperWA** [emmo-repo/EMMOntoPy#566]
From one of the latest attempts to run the `CI - Activate auto-merge for Dependabot PRs` workflow:

> The workflow is not valid. In .github/workflows/ci_automerge_dependabot.yml (Line: 10, Col: 11): Error from called workflow SINTEF/ci-cd/.github/workflows/ci_automerge_prs.yml@v2.1.0 (Line: 44, Col: 12): Unrecognized named-value: 'changes'. Located at position 1 within expression: changes

The actual run can be seen [here](https://github.com/emmo-repo/EMMOntoPy/actions/runs/4383619775).

Suggestions for "fixes":

1. Fix the immediate issue, i.e., fix the workflow file `.github/workflows/ci_automerge_depedabot.yml`.
2. Move over to using [SINTEF/ci-cd](https://SINTEF.github.io/ci-cd) for these "standard" workflows instead of implementing and maintaining them in this repo.

**Comment by francescalb** [comment]
@CasperWA I don't understand the error. It seems that it is already using the SINTEF/ci-cd?

**Comment by francescalb** [comment]
closed by  adding status checks for the ci/dependabot branch
