### ISSUE TITLE
BUG: pytest - missing remote file /0.5.0/electrochemicalquantities / ontology

### ISSUE THREAD

**Issue by markdoerr** [emmo-repo/EMMOntoPy#589]
With the current EMMOntoPy repo pytest throws this error at my setup - it seems that the the URL 
'http://emmo.info/electrochemistry/0.5.0/electrochemicalquantities' is pointing to nowhere...

` pytest
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.10.6, pytest-7.1.1, pluggy-1.0.0
rootdir: /mnt/lxdata/userdata/mark/source/projects/science/semantics/EMMOntoPy
plugins: cov-4.0.0, dash-2.7.0, anyio-3.5.0
collected 29 items / 1 error                                                                                                                                                                 

=========================================================================================== ERRORS ===========================================================================================
________________________________________________________________________ ERROR collecting tests/test_get_by_label.py _________________________________________________________________________
ontopy/ontology.py:660: in _load
    graph.parse(resolved_url, format=fmt)

[...]

ontopy/ontology.py:525: in load
    self._load(
ontopy/ontology.py:662: in _load
    raise EMMOntoPyException(
E   ontopy.utils.EMMOntoPyException: ('URL error', <HTTPError 404: 'Not Found'>, 'http://emmo.info/electrochemistry/0.5.0/electrochemicalquantities')
================================================================================== short test summary info ===================================================================================
ERROR tests/test_get_by_label.py - ontopy.utils.EMMOntoPyException: ('URL error', <HTTPError 404: 'Not Found'>, 'http://emmo.info/electrochemistry/0.5.0/electrochemicalquantities')
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================================== 1 error in 16.97s ========================================================================`

**Comment by francescalb** [comment]
Error in dependency. Fixed
