### ISSUE TITLE
Loading non-emmo-related ontologies

### ISSUE THREAD

**Issue by LorenaH84** [emmo-repo/EMMOntoPy#811]
We wanted to load a schema.org schema (https://schema.org/version/latest/schemaorg-current-https.ttl) using `get_ontology().load()`, but it returns an empty object. If we change the "Class" prefix to "owl" and the "rdfs:label" to "skos:prefLabel" it does load all the classes. The only difference with loading an emmo ontology is that the label has to be retrieved from `get_preferred_label()` instead of "prefLabel". Would be convenient if other ontologies could also be loaded directly from the original turtle files.

An example on what we had to change:

schema:AMRadioChannel a rdfs:Class ;
    rdfs:label "AMRadioChannel" ;
    
 to:
 
 schema:AMRadioChannel a owl:Class ;
    skos:prefLabel "AMRadioChannel" ;

**Comment by francescalb** [comment]
Hi, 

I see that the ontology loads with and that I can fetch the entities. My code:

```python
from ontopy import get_ontology
onto = get_ontology("https://schema.org/version/latest/schemaorg-current-https.ttl").load(emmo_based=False)
print(onto.AMRadioChannel)
```

However I see the same thing that you do when trying to list all the classes etc.
Some digging into owlready2 shows that there itis hardcoded that it looks for owl:classes.

I have to think a little about how to circumvent that. Hopefully direct access as shown above is useful for you.

**Comment by francescalb** [comment]
@LorenaH84 I have now added a fix that lets you access rdfs properties and classes. As you see the properties are accessed as strings of the iri and not as python objects. Hopefully this is sufficient for your needs.
